const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const table=Uint32Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc32(data){let c=0xffffffff;for(const b of data)c=table[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
class ZipWriter{
 constructor(target){this.target=target;this.temp=target+'.partial-'+crypto.randomUUID();this.entries=[];this.offset=0;}
 async open(){this.file=await fs.open(this.temp,'wx');}
 async write(buf){let n=0;while(n<buf.length){const r=await this.file.write(buf,n,buf.length-n,null);n+=r.bytesWritten;}this.offset+=buf.length;}
 async add(name,data){if(!/^[a-zA-Z0-9_./-]+$/.test(name)||name.includes('..')||name.startsWith('/')||this.entries.some(e=>e.name===name))throw Error('잘못된 패키지 경로');if(this.offset+data.length>2_000_000_000)throw Error('패키지는 2GB 이하로 나누어주세요.');const nb=Buffer.from(name),crc=crc32(data),offset=this.offset,head=Buffer.alloc(30);head.writeUInt32LE(0x04034b50);head.writeUInt16LE(20,4);head.writeUInt16LE(0x800,6);head.writeUInt32LE(crc,14);head.writeUInt32LE(data.length,18);head.writeUInt32LE(data.length,22);head.writeUInt16LE(nb.length,26);await this.write(head);await this.write(nb);await this.write(data);this.entries.push({name,nb,crc,size:data.length,offset});return {path:name,bytes:data.length,sha256:crypto.createHash('sha256').update(data).digest('hex')};}
 async finish(){const start=this.offset;for(const e of this.entries){const h=Buffer.alloc(46);h.writeUInt32LE(0x02014b50);h.writeUInt16LE(20,4);h.writeUInt16LE(20,6);h.writeUInt16LE(0x800,8);h.writeUInt32LE(e.crc,16);h.writeUInt32LE(e.size,20);h.writeUInt32LE(e.size,24);h.writeUInt16LE(e.nb.length,28);h.writeUInt32LE(e.offset,42);await this.write(h);await this.write(e.nb);}const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(this.entries.length,8);end.writeUInt16LE(this.entries.length,10);end.writeUInt32LE(this.offset-start,12);end.writeUInt32LE(start,16);await this.write(end);await this.file.sync();await this.file.close();this.file=null;await fs.rename(this.temp,this.target);}
 async cancel(){await this.file?.close();this.file=null;await fs.unlink(this.temp).catch(e=>{if(e.code!=='ENOENT')throw e;});}
}
const NOTICE={version:'region-studio-beta-1',text:'이 패키지에는 직접 선택한 이미지 전체, 선택한 영역 마스크, 이용 가능한 AI 보정 전후 결과와 클릭 정보가 포함됩니다. 로컬 파일 경로와 원본 파일명은 포함하지 않습니다. 오류 분석 동의와 모델 학습·개선 모델 배포 동의는 별도입니다. 원본 이미지 공개에 대한 동의는 포함하지 않습니다. 파일 생성만으로 서버에 전송되지 않습니다. 전달 전에 수집 담당자의 보관 기간·삭제 요청 방법을 확인하세요.'};
function validateRequest(r){if(!r||!r.consent?.analysis||!r.consent?.rights||r.consent.noticeVersion!==NOTICE.version)throw Error('제출 내용과 제공 권한에 동의해야 합니다.');if(!Array.isArray(r.items)||r.items.length<1||r.items.length>50)throw Error('한 패키지에는 1~50장을 선택하세요.');if(new Set(r.items.map(i=>i.id)).size!==r.items.length)throw Error('중복 이미지');for(const item of r.items){if(!Array.isArray(item.layers)||!item.layers.length||item.layers.some(i=>!Number.isInteger(i)||i<0||i>=30)||new Set(item.layers).size!==item.layers.length)throw Error('제출할 레이어를 선택하세요.');if(typeof item.group!=='string'||!item.group.trim()||item.group.length>100)throw Error('출처 묶음을 입력하세요.');if(!['own','permission','generated'].includes(item.provenance))throw Error('이미지 제공 근거를 선택하세요.');if(typeof item.style!=='string'||!item.style.trim()||item.style.length>200)throw Error('그림체 특징을 입력하세요.');}return r;}
function registerSubmission({handle,store,dialog,getWindow,app,nativeImage,atomic}){
 const sessions=new Map();
 handle('beta-profile',async()=>{const file=path.join(app.getPath('userData'),'beta-participant.json');let profile;try{profile=JSON.parse(await fs.readFile(file,'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;profile={id:crypto.randomUUID()};await atomic(file,JSON.stringify(profile));}return {participantId:profile.id,notice:NOTICE};});
 handle('beta-begin',async request=>{validateRequest(request);for(const item of request.items){const state=await store.read(item.id);if((!state?.approved||state.skipped)||item.layers.some(i=>!state.layers[i]||!Buffer.from(state.layers[i].mask,'base64').some(x=>x)))throw Error('정답 확정된 비어 있지 않은 레이어만 제출할 수 있습니다.');}
 const submissionId=crypto.randomUUID(),r=await dialog.showSaveDialog(getWindow(),{title:'베타 제출 패키지 저장',defaultPath:'Region-Studio-Beta-'+submissionId.slice(0,8)+'.zip',filters:[{name:'제출 패키지',extensions:['zip']}]});if(r.canceled)return null;if(!r.filePath?.toLowerCase().endsWith('.zip'))throw Error('ZIP 파일로 저장하세요.');const writer=new ZipWriter(r.filePath);await writer.open();const profile=JSON.parse(await fs.readFile(path.join(app.getPath('userData'),'beta-participant.json'),'utf8'));sessions.set(submissionId,{writer,request,images:[],assets:[],participantId:profile.id});return {token:submissionId};});
 handle('beta-add',async(token,id,image)=>{const s=sessions.get(token);if(!s)throw Error('제출 세션이 없습니다.');const item=s.request.items.find(i=>i.id===id);if(!item||s.images.some(i=>i.localId===id))throw Error('선택하지 않았거나 중복된 이미지');const state=await store.read(id);if((!state?.approved||state.skipped))throw Error('확정 상태가 변경되었습니다.');if(typeof image!=='string'||!image.startsWith('data:image/png;base64,'))throw Error('PNG가 필요합니다.');const decoded=nativeImage.createFromBuffer(Buffer.from(image.slice(22),'base64')),size=decoded.getSize();if(size.width!==state.width||size.height!==state.height)throw Error('원본과 마스크 크기가 다릅니다.');const normalized=decoded.toPNG(),folder='image-'+String(s.images.length+1).padStart(4,'0');const asset=await s.writer.add(folder+'/image.png',normalized);s.assets.push(asset);const masks=[];
 for(const index of item.layers){const layer=state.layers[index],record={id:index+1,anchors:layer.points||[],promptHistory:layer.promptHistory||null,refinement:layer.refinement||null,masks:{}};for(const [key,suffix] of [['mask','final'],['initialMask','initial-ai'],['modelMask','latest-ai'],['refinedMask','geometry']]){if(!layer[key]){record.masks[suffix]=null;continue;}const mask=Buffer.from(layer[key],'base64');if(mask.length!==state.width*state.height)throw Error('마스크 크기 불일치');const rgba=Buffer.alloc(mask.length*4);for(let p=0;p<mask.length;p++){rgba[p*4]=rgba[p*4+1]=rgba[p*4+2]=mask[p];rgba[p*4+3]=255;}const data=nativeImage.createFromBitmap(rgba,{width:state.width,height:state.height}).toPNG(),name=folder+'/mask-'+String(masks.length+1).padStart(3,'0')+'-'+suffix+'.png';s.assets.push(await s.writer.add(name,data));record.masks[suffix]=name;}masks.push(record);}
 s.images.push({localId:id,id:folder,image:asset.path,imageHash:asset.sha256,width:state.width,height:state.height,sourceGroup:item.group.trim(),style:item.style.trim(),provenance:item.provenance,metrics:state.metrics||null,reviewStatus:'pending',split:'unassigned',layers:masks});return {count:s.images.length};});
 handle('beta-finish',async token=>{const s=sessions.get(token);if(!s||s.images.length!==s.request.items.length)throw Error('일부 이미지가 아직 준비되지 않았습니다.');const manifest={format:'region-studio-beta',version:1,submissionId:token,createdAt:new Date().toISOString(),participantId:s.participantId,appVersion:app.getVersion(),model:'Xenova/slimsam-77-uniform',runtime:'transformers.js@3.5.0',consent:{analysis:true,training:!!s.request.consent.training,modelDistribution:!!s.request.consent.training,rightsConfirmed:true,publicImageRelease:false,notice:NOTICE,recordedAt:new Date().toISOString()},notes:String(s.request.notes||'').slice(0,2000),images:s.images.map(({localId,...rest})=>rest),assets:s.assets};await s.writer.add('manifest.json',Buffer.from(JSON.stringify(manifest,null,2)));await s.writer.add('README.txt',Buffer.from('Region Studio beta submission\nReview status: pending. Do not train before quality and consent review.\nBinary masks are annotation data. Anti-aliasing is a rendering-only effect.\nKeep source groups and duplicate image hashes together when assigning train/validation/test sets.\n'));await s.writer.finish();await atomic(path.join(app.getPath('userData'),'beta-receipts',token+'.json'),JSON.stringify({submissionId:token,path:s.writer.target,createdAt:manifest.createdAt,training:manifest.consent.training,zipSha256:await fileHash(s.writer.target)}));sessions.delete(token);return {path:s.writer.target,submissionId:token,count:s.images.length};});
 handle('beta-cancel',async token=>{const s=sessions.get(token);if(s){await s.writer.cancel();sessions.delete(token);}return true;});
}
async function fileHash(file){const hash=crypto.createHash('sha256');for await(const chunk of require('node:fs').createReadStream(file))hash.update(chunk);return hash.digest('hex');}
module.exports={ZipWriter,validateRequest,NOTICE,registerSubmission};
