import {compose,outsideChanges,brush} from './core.mjs';
import {refineMask} from './refine.mjs';
import {setupViewport} from './viewport.mjs';
import {setupSubmission} from './submission-ui.mjs';
const $=id=>document.getElementById(id),api=window.desktop,canvas=$('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true}),marks=$('marks'),mctx=marks.getContext('2d');
let source,w=0,h=0,layers=[],active=0,files=[],id=null,approved=false,skipped=false,tool='positive',worker,ready=false,busy=false,navigating=false,showOriginal=false,drag=false,lastPoint,history=[],candidates=[],dirty=false,timer,saveQueue=Promise.resolve(),revision=0,exporting=false;
canvas.width=0;marks.width=0;
const maskIndices=new WeakMap(),maskOverlays=new WeakMap(),encodedMasks=new WeakMap();let frame=0,frameTimer,auditTimer,lastOverlay=null,lastResult;
const view=setupViewport({viewport:$('viewport'),canvas,wrap:$('canvasWrap'),zoom:$('zoom'),brush:$('brush'),brushValue:$('brushValue'),getSize:()=>({w,h}),getTool:()=>tool,canPaint:()=>!!source&&!busy&&!showOriginal&&!exporting});
function invalidateMask(){if(current()){encodedMasks.delete(current().mask);maskIndices.delete(current().mask);maskOverlays.delete(current().mask);}lastOverlay=null;}
function refineCurrent(raw){const result=refineMask(raw,w,h,current().points,{fill:$('fillHoles').checked});current().mask=result.mask;current().refinedMask=result.mask.slice();current().refinement={fill:$('fillHoles').checked};invalidateMask();$('refineInfo').textContent='닫힌 빈틈 채움 '+result.filled.toLocaleString()+' px';}
function applyCandidate(){const raw=candidates[Number($('candidate').value)];if(!current().initialMask)current().initialMask=raw.slice();current().modelMask=raw.slice();refineCurrent(raw);changed();render();}
$('refine').onclick=async()=>{if(!current()||busy||exporting)return;if(!current().points.some(p=>p.label===1)){status('포함 클릭 지점을 먼저 추가하세요.');return;}snapshot();try{if(!ready)await prepare(id);setBusy(true);worker.postMessage({type:'decode',points:current().points});}catch(e){setBusy(false);fail(e);}};
const current=()=>layers[active],status=t=>$('status').textContent=t;
function fresh(){return {name:`영역 ${layers.length+1}`,mask:new Uint8Array(w*h),color:'#ffffff',strength:1,visible:true,points:[]};}
function b64(a){if(encodedMasks.has(a))return encodedMasks.get(a);let s='';for(let i=0;i<a.length;i+=16384)s+=String.fromCharCode(...a.subarray(i,i+16384));const result=btoa(s);encodedMasks.set(a,result);return result;}
const unpack=s=>s.layers.map(l=>{const out={...l,color:l.color?.toLowerCase()==='#000000'?'#000000':'#ffffff',points:l.points||[]};for(const key of ['mask','initialMask','modelMask','refinedMask'])if(l[key])out[key]=Uint8Array.from(atob(l[key]),c=>c.charCodeAt(0));return out;});
let metrics={},lastAction=0;function record(key){const now=performance.now(),delta=now-lastAction;if(lastAction&&delta<30000)metrics.activeMs=(metrics.activeMs||0)+Math.round(delta);lastAction=now;metrics[key]=(metrics[key]||0)+1;}
function payload(){return {version:2,width:w,height:h,approved,skipped,metrics,layers:layers.map(l=>{const out={...l};for(const key of ['mask','initialMask','modelMask','refinedMask'])if(l[key])out[key]=b64(l[key]);return out;})};}
function snapshot(){history.push({layers:layers.map(l=>({...l,mask:l.mask.slice(),points:l.points.map(p=>({...p}))})),active});if(history.length>8)history.shift();}
function changed(){skipped=false;dirty=true;approved=false;revision++;clearTimeout(timer);timer=setTimeout(()=>flush().catch(fail),700);$('saveStatus').textContent='저장 대기…';approvalUI();}
async function flush(){clearTimeout(timer);if(!id||!dirty){await saveQueue;return;}const saving=id,rev=revision,s=payload();$('saveStatus').textContent='저장 중…';const task=saveQueue.catch(()=>{}).then(()=>api.save(saving,s));saveQueue=task;await task;if(id===saving&&revision===rev){dirty=false;$('saveStatus').textContent='자동 저장됨';}const f=files.find(f=>f.id===saving);if(f)f.status=s.skipped?'skipped':s.approved?'approved':'working';const row=$('files').querySelector('[data-image-id="'+saving+'"] small');if($('filter').value==='all'&&row)row.textContent=s.skipped?'스킵 · 원본 저장':s.approved?'정답 확정':'작업 중';else list();}
function fail(e){status(e.message||String(e));$('saveStatus').textContent='처리 실패 · '+(e.message||e);}
function approvalUI(){$('skip').textContent=skipped?'스킵 해제':'스킵 · 원본 저장';$('approve').textContent=approved?'✓ 정답 확정됨 · 해제':'현재 마스크 정답 확정';$('approve').classList.toggle('approved',approved);}
function resetCandidates(){candidates=[];$('candidate').replaceChildren(new Option('영역을 클릭하세요',''));$('candidate').disabled=true;}
function controls(){if(!current())return;$('color').value=current().color;$('strength').value=current().strength*100;$('strengthValue').value=Math.round(current().strength*100)+'%';$('layers').replaceChildren();layers.forEach((l,i)=>{const row=document.createElement('div');row.className='layer'+(i===active?' selected':'');const cb=document.createElement('input');cb.type='checkbox';cb.checked=l.visible;cb.setAttribute('aria-label','레이어 '+(i+1)+' 표시');cb.onchange=()=>{snapshot();l.visible=cb.checked;changed();render();};const b=document.createElement('button'),dot=document.createElement('i');dot.style.background=l.color;b.append(dot,document.createTextNode('레이어 '+(i+1)));b.onclick=()=>{if(busy)return;active=i;resetCandidates();controls();render();};row.append(cb,b);$('layers').append(row);});approvalUI();}
function render(){if(!frame){frame=requestAnimationFrame(draw);frameTimer=setTimeout(draw,50);}}
function draw(){cancelAnimationFrame(frame);clearTimeout(frameTimer);frame=0;if(!source)return;const src=source,result=compose(src,layers,maskIndices,w,h);lastResult=result;ctx.putImageData(new ImageData(showOriginal?src.slice():result,w,h),0,0);
const l=current(),enabled=!showOriginal&&$('overlay').checked,points=JSON.stringify(l?.points||[]);
if(!lastOverlay||lastOverlay.mask!==l?.mask||lastOverlay.points!==points||lastOverlay.enabled!==enabled){mctx.clearRect(0,0,w,h);if(enabled&&l){let d=maskOverlays.get(l.mask);if(!d){d=mctx.createImageData(w,h);for(let p=0;p<w*h;p++)if(l.mask[p]){d.data[p*4]=72;d.data[p*4+1]=225;d.data[p*4+2]=205;d.data[p*4+3]=75;}maskOverlays.set(l.mask,d);}mctx.putImageData(d,0,0);for(const p of l.points){mctx.beginPath();mctx.arc(p.x*w,p.y*h,5*Math.max(w/800,1),0,Math.PI*2);mctx.fillStyle=p.label?'#44efc5':'#ff637d';mctx.fill();mctx.strokeStyle='#17202b';mctx.lineWidth=2;mctx.stroke();}}lastOverlay={mask:l?.mask,points,enabled};}
clearTimeout(auditTimer);auditTimer=setTimeout(()=>{if(source===src&&lastResult===result)$('integrity').textContent='선택 영역 밖 픽셀 변경: '+outsideChanges(src,result,layers);},180);view.updateCursor();}
function fit(){view.fit();}
function filtered(){const q=$('search').value.toLowerCase(),f=$('filter').value;return files.filter(x=>(f==='all'||x.status===f)&&x.name.toLowerCase().includes(q));}
function list(){const data=filtered();$('count').textContent=`${data.length} / ${files.length}장`;$('files').replaceChildren();for(const f of data){const b=document.createElement('button');b.className='file'+(f.id===id?' active':'');b.dataset.imageId=f.id;const im=document.createElement('img');im.loading='lazy';im.src='./image/'+f.id+'?v='+f.signature;im.alt='';const s=document.createElement('span');s.append(document.createTextNode(f.name));const small=document.createElement('small');small.textContent=({new:'미작업',working:'작업 중',approved:'정답 확정',skipped:'스킵 · 원본 저장'})[f.status]+(f.prepared?' · 분석 준비됨':'');s.append(small);b.title=f.name;b.append(im,s);b.onclick=()=>select(f.id).catch(fail);$('files').append(b);}}
async function pixels(imageId){const im=new Image();im.src='./image/'+imageId+'?v='+files.find(f=>f.id===imageId)?.signature;await im.decode();if(im.naturalWidth*im.naturalHeight>5000000)throw Error('500만 픽셀 이하 이미지를 사용하세요.');const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0);return {width:c.width,height:c.height,data:x.getImageData(0,0,c.width,c.height).data};}
async function select(next){if(next===id||navigating||exporting||busy)return;navigating=true;try{await flush();const [p,s]=await Promise.all([pixels(next),api.read(next)]);ready=false;source=p.data;w=p.width;h=p.height;id=next;canvas.width=marks.width=w;canvas.height=marks.height=h;lastOverlay=null;layers=[];layers=s?unpack(s):[fresh()];if(!layers.length)layers.push(fresh());approved=!!s?.approved;skipped=!!s?.skipped;metrics={...(s?.metrics||{})};lastAction=0;dirty=false;active=0;history=[];resetCandidates();$('empty').hidden=true;$('filename').textContent=files.find(f=>f.id===id).name;$('dimensions').textContent=`${w} × ${h} px`;$('saveStatus').textContent=s?'저장된 작업 복원':'미작업';status('AI 분석 또는 브러시로 영역을 선택하세요.');controls();list();fit();render();if(files.find(f=>f.id===id)?.prepared)await prepare(id);}finally{navigating=false;}}
$('folder').onclick=async()=>{if(busy||exporting||navigating)return;try{await flush();const r=await api.openFolder();if(!r)return;files=r.files;id=null;source=null;w=h=0;layers=[];worker?.terminate();worker=null;ready=false;canvas.width=marks.width=0;$('empty').hidden=false;$('folderName').textContent=r.folder;list();if(files.length)await select(files[0].id);else status('이 폴더에 PNG, JPG, WebP 이미지가 없습니다.');}catch(e){fail(e);}};
async function move(delta){const data=filtered(),i=data.findIndex(f=>f.id===id),f=data[i+delta];if(f)await select(f.id);}
$('prev').onclick=()=>move(-1).catch(fail);$('next').onclick=()=>move(1).catch(fail);$('search').oninput=$('filter').onchange=list;
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='ArrowLeft')move(-1).catch(fail);if(e.key==='ArrowRight')move(1).catch(fail);if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo();}});
function setBusy(v){v=v||batchPreparing;busy=v;$('analyze').disabled=v;$('candidate').disabled=v||!candidates.length;}
let pendingPrepare=null,batchPreparing=false,stopPrepare=false;
function ensureWorker(){if(worker)return;worker=new Worker('./segment.worker.mjs',{type:'module'});worker.onmessage=async({data:m})=>{if(m.type==='status'){if(!batchPreparing)status(m.text);return;}if(m.type==='ready'){const pending=pendingPrepare;pendingPrepare=null;try{if(m.cache)await api.cacheWrite(pending.id,m.cache);const f=files.find(f=>f.id===pending.id);if(f)f.prepared=true;ready=pending.id===id;pending.resolve();}catch(e){pending.reject(e);}return;}if(m.type==='masks'){candidates=m.candidates;const best=m.scores.indexOf(Math.max(...m.scores));$('candidate').replaceChildren(...m.scores.map((_,i)=>new Option('후보 '+(i+1)+(i===best?' · 추천':''),i)));$('candidate').value=best;setBusy(false);applyCandidate();status('선택 완료 · 앵커 위치를 기준으로 인식했습니다.');}if(m.type==='error'){if(pendingPrepare){pendingPrepare.reject(Error(m.text));pendingPrepare=null;}setBusy(false);fail(Error(m.text));}};worker.onerror=e=>{pendingPrepare?.reject(Error(e.message));pendingPrepare=null;worker.terminate();worker=null;ready=false;setBusy(false);fail(e);};}
async function prepare(imageId){setBusy(true);try{ensureWorker();const cache=await api.cacheRead(imageId);const p=cache?null:(imageId===id?{data:source,width:w,height:h}:await pixels(imageId));await new Promise((resolve,reject)=>{pendingPrepare={id:imageId,resolve,reject};worker.postMessage(cache?{type:'restore',cache}:{type:'encode',pixels:p.data.slice().buffer,width:p.width,height:p.height});});}finally{if(!batchPreparing)setBusy(false);}}
$('analyze').onclick=async()=>{if(!source||busy||exporting)return;try{await prepare(id);list();status('AI 준비 완료 · 포함할 곳을 클릭하세요.');}catch(e){fail(e);}};
$('pausePrepare').onclick=()=>{stopPrepare=true;$('pausePrepare').disabled=true;};
$('prepareAll').onclick=async()=>{if(!files.length||busy||exporting||navigating)return;batchPreparing=true;stopPrepare=false;setBusy(true);$('pausePrepare').hidden=false;$('pausePrepare').disabled=false;$('prepPanel').hidden=false;$('prepProgress').max=files.length;let done=0,failed=0;try{await flush();for(const f of files){if(stopPrepare)break;try{if(!f.prepared)await prepare(f.id);}catch(e){failed++;}done++;$('prepProgress').value=done;$('prepText').textContent=done+' / '+files.length+'장 · 실패 '+failed;}ready=false;if(id&&files.find(f=>f.id===id)?.prepared)await prepare(id);list();status((stopPrepare?'분석 준비 중지':'분석 준비 완료')+' · '+done+'장 · 실패 '+failed+'장. 다시 실행하면 준비된 이미지는 건너뜁니다.');}finally{batchPreparing=false;setBusy(false);$('pausePrepare').hidden=true;}};
$('rescan').onclick=async()=>{if(busy||exporting||navigating)return;try{await flush();const previous=files,selected=id,r=await api.rescan();if(!r)return;files=r.files;const changed=files.filter(f=>previous.find(p=>p.id===f.id)?.signature!==f.signature).length;id=null;source=null;layers=[];canvas.width=marks.width=0;ready=false;list();if(files.length)await select(files.some(f=>f.id===selected)?selected:files[0].id);else $('empty').hidden=false;status('위치 스캔 완료 · 새 이미지 또는 교체 '+changed+'장. 교체된 이미지의 이전 마스크와 분석 캐시는 적용하지 않았습니다.');}catch(e){fail(e);}};
$('skip').onclick=async()=>{if(!source||busy||exporting)return;skipped=!skipped;approved=false;dirty=true;revision++;approvalUI();try{await flush();status(skipped?'최종 폴더에 원본 그대로 저장합니다. 학습·베타 데이터에서는 제외합니다.':'스킵을 해제했습니다.');}catch(e){fail(e);}};

function point(e){const b=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-b.left)/b.width)),y:Math.max(0,Math.min(1,(e.clientY-b.top)/b.height))};}
function paint(p){const r=Number($('brush').value)/2;const prev=lastPoint||p,n=Math.max(1,Math.ceil(Math.hypot((p.x-prev.x)*w,(p.y-prev.y)*h)/Math.max(1,r/2)));for(let i=1;i<=n;i++)brush(current().mask,w,h,(prev.x+(p.x-prev.x)*i/n)*w,(prev.y+(p.y-prev.y)*i/n)*h,r,tool==='erase'?0:255);lastPoint=p;record('brushMoves');invalidateMask();changed();render();}
canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{if(!source||busy||navigating||exporting||showOriginal)return;const p=point(e);if(e.ctrlKey){const rect=canvas.getBoundingClientRect();const i=current().points.findIndex(q=>Math.hypot((q.x-p.x)*rect.width,(q.y-p.y)*rect.height)<=12);if(i>=0){snapshot();current().points.splice(i,1);invalidateMask();changed();render();status('앵커 삭제 · 부위 다시 인식 버튼으로 마스크를 갱신하세요.');}return;}if(tool==='paint'||tool==='erase'){snapshot();record('brushStrokes');drag=true;lastPoint=null;canvas.setPointerCapture(e.pointerId);paint(p);}else{if(!ready){status('먼저 AI 분석을 누르세요.');return;}const label=tool==='negative'||e.button===2?0:1;if(!label&&!current().points.length){status('포함할 곳을 먼저 클릭하세요.');return;}snapshot();current().points.push({...p,label});record(label?'includeClicks':'excludeClicks');current().promptHistory=[...(current().promptHistory||[]),{...p,label,activeMs:metrics.activeMs||0}];setBusy(true);render();worker.postMessage({type:'decode',points:current().points});}};
canvas.onpointermove=e=>{if(drag)paint(point(e));};canvas.onpointerup=canvas.onpointercancel=()=>{drag=false;lastPoint=null;};
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));});
$('brush').oninput=()=>{$('brushValue').value=$('brush').value+' px';};$('candidate').onchange=()=>{if(!current())return;snapshot();applyCandidate();};
for(const name of ['color','strength']){$(name).onfocus=()=>{if(current())snapshot();};$(name).oninput=()=>{if(!current()||busy)return;current().color=$('color').value;current().strength=Number($('strength').value)/100;$('strengthValue').value=$('strength').value+'%';changed();render();};$(name).onchange=controls;}
$('overlay').onchange=render;$('original').onclick=()=>{showOriginal=!showOriginal;$('original').textContent=showOriginal?'편집 결과':'원본 보기';render();};
$('clear').onclick=()=>{if(!current()||busy)return;snapshot();current().mask.fill(0);current().points=[];invalidateMask();resetCandidates();changed();render();};
function undo(){if(busy||exporting||navigating)return;record('undoCount');const s=history.pop();if(s){layers=s.layers;active=s.active;resetCandidates();changed();controls();render();}};
$('newLayer').onclick=()=>{if(!source||busy)return;if(layers.length>=30){status('이미지당 레이어는 최대 30개입니다.');return;}snapshot();layers.push(fresh());active=layers.length-1;resetCandidates();changed();controls();render();};
$('deleteLayer').onclick=()=>{if(!current()||busy)return;snapshot();layers.splice(active,1);if(!layers.length)layers.push(fresh());active=Math.min(active,layers.length-1);resetCandidates();changed();controls();render();};
$('approve').onclick=async()=>{if(!source||busy)return;if(!layers.some(l=>l.mask.some(x=>x))){status('확정할 마스크가 없습니다.');return;}skipped=false;approved=!approved;dirty=true;revision++;approvalUI();try{await flush();status(approved?'학습용 정답으로 저장했습니다.':'정답 확정을 해제했습니다.');}catch(e){fail(e);}};
function png(data,width,height){const c=document.createElement('canvas');c.width=width;c.height=height;c.getContext('2d').putImageData(new ImageData(data,width,height),0,0);return c.toDataURL('image/png');}
async function exportItems(kind){if(exporting||busy||navigating)return;try{await flush();const items=files.filter(f=>kind==='dataset'?f.status==='approved':f.status!=='new');if(!items.length){status(kind==='dataset'?'정답 확정한 이미지가 없습니다.':'저장된 작업이 없습니다.');return;}const token=await api.destination(kind);if(!token)return;exporting=true;document.body.classList.add('exporting');const manifest=[];for(let i=0;i<items.length;i++){const f=items[i],s=await api.read(f.id);if(!s)continue;const ls=unpack(s);status(`내보내는 중 ${i+1} / ${items.length}`);if(kind==='results'&&s.skipped){await api.write(token,f.id,{skipped:true});continue;}if(kind==='results'){const p=await pixels(f.id);await api.write(token,f.id,{image:png(compose(p.data,ls,undefined,p.width,p.height),p.width,p.height)});}else{const nonempty=ls.filter(l=>l.mask.some(x=>x));const masks=nonempty.map(l=>{const rgba=new Uint8ClampedArray(s.width*s.height*4);for(let p=0;p<l.mask.length;p++){rgba[p*4]=rgba[p*4+1]=rgba[p*4+2]=l.mask[p]?255:0;rgba[p*4+3]=255;}return png(rgba,s.width,s.height);});await api.write(token,f.id,{masks});manifest.push({id:f.id,annotation:f.id+'/annotation.json',split:parseInt(f.id.slice(0,2),16)%5===0?'validation':'train'});}}const dir=await api.finish(token,{images:manifest});status('내보내기 완료: '+dir);}catch(e){fail(e);}finally{exporting=false;document.body.classList.remove('exporting');}}
$('batch').onclick=()=>exportItems('results');$('dataset').onclick=()=>exportItems('dataset');
setupSubmission({api,button:$('beta'),getFiles:()=>files,flush,pixels,png,unpack,lock:v=>{exporting=v;},blocked:()=>busy||exporting||navigating,status});
api.onClose(async()=>{try{if(busy||exporting)throw Error('AI 분석 또는 내보내기가 끝난 뒤 닫아주세요.');await flush();api.closeReady();}catch(e){api.closeFailed(e.message);}});
