import {mergeLocal} from './boundary.mjs';
let anchorEdit=null;
import {compose,outsideChanges,brushSegment,edgeCoverage} from './core.mjs';
import {refineMask} from './refine.mjs';
import {setupViewport} from './viewport.mjs';
import {setupPanels} from './panels.mjs';
import {encodeResult} from './result-file.mjs';
import {setupSubmission} from './submission-ui.mjs';
const $=id=>document.getElementById(id),api=window.desktop,canvas=$('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true}),marks=$('marks'),mctx=marks.getContext('2d');
let preferenceSave=Promise.resolve(),preferenceTimer,defaultStrength=1;let defaultColor='#ffffff';
const settingRanges={brush:[2,300],edgeStrength:[0,100],anchorRadius:[5,100],fillConfidence:[60,100],lineGap:[0,4],smoothAmount:[1,6],strength:[0,100]};
const preferencesReady=api.preferencesRead().then(p=>{panels.restore(p);if(['#ffffff','#000000'].includes(p.color))defaultColor=p.color;$('color').value=defaultColor;for(const [key,[min,max]] of Object.entries(settingRanges))if(Number.isFinite(p[key])&&p[key]>=min&&p[key]<=max){$(key).value=p[key];const out=$(key+'Value');if(out)out.value=p[key]+(['brush','lineGap'].includes(key)?' px':['anchorRadius','fillConfidence','strength'].includes(key)?'%':'');}defaultStrength=Number($('strength').value)/100;for(const key of ['fillHoles','overlay'])if(typeof p[key]==='boolean')$(key).checked=p[key];if(typeof p.refinementOpen==='boolean')document.querySelector('.refinement').open=p.refinementOpen;if(['positive','negative','paint','erase'].includes(p.tool)){tool=p.tool;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));}}).catch(e=>fail(e));
const panels=setupPanels(queueSetting);
let settingsPatch={};function queueSetting(patch){Object.assign(settingsPatch,patch);clearTimeout(preferenceTimer);preferenceTimer=setTimeout(saveSettings,150);}function saveSettings(){clearTimeout(preferenceTimer);if(!Object.keys(settingsPatch).length)return;const patch=settingsPatch;settingsPatch={};preferenceSave=preferenceSave.catch(()=>{}).then(()=>api.preferencesSave(patch));preferenceSave.catch(fail);}
for(const key of Object.keys(settingRanges))$(key).addEventListener('input',()=>{queueSetting({[key]:Number($(key).value)});if(key==='strength')defaultStrength=Number($(key).value)/100;});for(const key of ['fillHoles','overlay'])$(key).addEventListener('change',()=>queueSetting({[key]:$(key).checked}));document.querySelector('.refinement').addEventListener('toggle',()=>queueSetting({refinementOpen:document.querySelector('.refinement').open}));document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>queueSetting({tool:b.dataset.tool})));

let source,sourceCanvas,w=0,h=0,layers=[],active=0,files=[],id=null,approved=false,skipped=false,tool='positive',worker,ready=false,busy=false,navigating=false,showOriginal=false,drag=false,lastPoint,history=[],candidates=[],dirty=false,timer,saveQueue=Promise.resolve(),revision=0,exporting=false;
canvas.width=0;marks.width=0;
const maskIndices=new WeakMap(),maskOverlays=new WeakMap(),encodedMasks=new WeakMap(),maskVersions=new WeakMap(),maskIds=new WeakMap();let nextMaskId=0,frame=0,frameTimer,auditTimer,lastOverlay=null,lastResult;
function maskId(mask){if(!maskIds.has(mask))maskIds.set(mask,++nextMaskId);return maskIds.get(mask);}
const view=setupViewport({viewport:$('viewport'),canvas,wrap:$('canvasWrap'),zoom:$('zoom'),brush:$('brush'),brushValue:$('brushValue'),getSize:()=>({w,h}),getTool:()=>tool,canPaint:()=>!!source&&!busy&&!showOriginal&&!exporting,isPainting:()=>drag});
function invalidateMask(){if(current()){encodedMasks.delete(current().mask);maskIndices.delete(current().mask);maskOverlays.delete(current().mask);maskVersions.set(current().mask,(maskVersions.get(current().mask)||0)+1);}lastOverlay=null;}
let boundaryWorker,boundarySerial=0;const boundaryPending=new Map();
function boundaryTask(type,data={}){if(!boundaryWorker){boundaryWorker=new Worker('./boundary.worker.mjs',{type:'module'});boundaryWorker.onmessage=({data:r})=>{const p=boundaryPending.get(r.request);if(!p)return;boundaryPending.delete(r.request);r.error?p.reject(Error(r.error)):p.resolve(r);};boundaryWorker.onerror=e=>{for(const p of boundaryPending.values())p.reject(Error(e.message));boundaryPending.clear();boundaryWorker.terminate();boundaryWorker=null;};}return new Promise((resolve,reject)=>{const request=++boundarySerial;boundaryPending.set(request,{resolve,reject});boundaryWorker.postMessage({type,request,...data});});}
const boundaryOptions=()=>({strength:Number($('edgeStrength').value),radius:Number($('anchorRadius').value),confidence:Number($('fillConfidence').value),gap:Number($('lineGap').value)});
async function refineCurrent(raw){const options=boundaryOptions(),positives=current().points.filter(p=>p.label===1),negatives=current().points.filter(p=>p.label===0);const bounded=await boundaryTask('select',{mask:raw,points:positives,options});const closed=await boundaryTask('select',{mask:bounded.mask,points:positives,options:{...options,lineOnly:true}});const result=refineMask(closed.accepted?closed.mask:bounded.mask,w,h,positives,{fill:$('fillHoles').checked});let mask=anchorEdit?mergeLocal(anchorEdit.mask,result.mask,w,h,anchorEdit.point,options.radius):result.mask,unmatched=0;if(anchorEdit){if(negatives.length)mask=(await boundaryTask('negative',{mask,points:negatives,protectedPoints:positives,options})).mask;}else{const reconciled=await boundaryTask('reconcile',{mask,points:current().points,options});mask=reconciled.mask;unmatched=reconciled.unmatched;}current().mask=mask;current().refinedMask=mask.slice();current().refinement={...options,fill:$('fillHoles').checked,lineConfidence:closed.confidence,unmatched};invalidateMask();}
async function applyCandidate(){if(!current())return;setBusy(true);try{const raw=candidates[Number($('candidate').value)];if(!current().initialMask)current().initialMask=raw.slice();current().modelMask=raw.slice();await refineCurrent(raw);changed();render();}catch(e){fail(e);}finally{setBusy(false);}}
$('smooth').onclick=async()=>{if(!current()||busy||exporting)return;snapshot();setBusy(true);try{const r=await boundaryTask('smooth',{mask:current().mask,points:current().points,amount:Number($('smoothAmount').value)});current().mask=r.mask;record('curveCorrections');invalidateMask();changed();render();status('곡선 보정 완료 · 변경 '+r.mask.reduce((n,v,i)=>n+(v!==history[history.length-1].layers[active].mask[i]),0)+' px · Ctrl+Z로 되돌릴 수 있습니다.');}catch(e){fail(e);}finally{setBusy(false);}};
for(const [name,suffix] of [['edgeStrength',''],['anchorRadius','%'],['fillConfidence','%'],['lineGap',' px'],['smoothAmount','']])$(name).oninput=()=>{$(name+'Value').value=$(name).value+suffix;};
$('refine').onclick=async()=>{if(!current()||busy||exporting)return;if(!current().points.some(p=>p.label===1)){status('포함 클릭 지점을 먼저 추가하세요.');return;}snapshot();anchorEdit=null;try{if(!ready)await prepare(id);setBusy(true);worker.postMessage({type:'decode',points:current().points.filter(p=>p.label===1)});}catch(e){setBusy(false);fail(e);}};
const current=()=>layers[active],status=t=>$('status').textContent=t;
function fresh(){return {name:`영역 ${layers.length+1}`,mask:new Uint8Array(w*h),color:defaultColor,strength:defaultStrength,visible:true,points:[]};}
function b64(a){if(encodedMasks.has(a))return encodedMasks.get(a);let s='';for(let i=0;i<a.length;i+=16384)s+=String.fromCharCode(...a.subarray(i,i+16384));const result=btoa(s);encodedMasks.set(a,result);return result;}
const unpack=s=>s.layers.map(l=>{const out={...l,color:l.color?.toLowerCase()==='#000000'?'#000000':'#ffffff',points:l.points||[]};for(const key of ['mask','initialMask','modelMask','refinedMask'])if(l[key])out[key]=Uint8Array.from(atob(l[key]),c=>c.charCodeAt(0));return out;});
let metrics={},lastAction=0;function record(key){const now=performance.now(),delta=now-lastAction;if(lastAction&&delta<30000)metrics.activeMs=(metrics.activeMs||0)+Math.round(delta);lastAction=now;metrics[key]=(metrics[key]||0)+1;}
function payload(){return {version:2,width:w,height:h,approved,skipped,metrics,layers:layers.map(l=>{const out={...l};for(const key of ['mask','initialMask','modelMask','refinedMask'])if(l[key])out[key]=b64(l[key]);return out;})};}
function snapshot(){history.push({layers:layers.map(l=>({...l,mask:l.mask.slice(),points:l.points.map(p=>({...p}))})),active});if(history.length>8)history.shift();}
function changed(){skipped=false;dirty=true;approved=false;revision++;clearTimeout(timer);timer=setTimeout(()=>{if(!drag)flush().catch(fail);},700);$('saveStatus').textContent='저장 대기…';approvalUI();}
async function flush(){saveSettings();await preferenceSave;clearTimeout(timer);if(!id||!dirty){await saveQueue;return;}const saving=id,rev=revision,s=payload();$('saveStatus').textContent='저장 중…';const task=saveQueue.catch(()=>{}).then(()=>api.save(saving,s));saveQueue=task;await task;if(id===saving&&revision===rev){dirty=false;$('saveStatus').textContent='자동 저장됨';}const f=files.find(f=>f.id===saving);if(f)f.status=s.skipped?'skipped':s.approved?'approved':'working';const row=$('files').querySelector('[data-image-id="'+saving+'"] small');if($('filter').value==='all'&&row)row.textContent=s.skipped?'스킵 · 원본 저장':s.approved?'정답 확정':'작업 중';else list();}
function fail(e){status(e.message||String(e));$('saveStatus').textContent='처리 실패 · '+(e.message||e);}
function approvalUI(){$('skip').textContent=skipped?'스킵 해제':'스킵 · 원본 저장';$('approve').textContent=approved?'✓ 정답 확정됨 · 해제':'현재 마스크 정답 확정';$('approve').classList.toggle('approved',approved);}
function resetCandidates(){anchorEdit=null;candidates=[];$('candidate').replaceChildren(new Option('영역을 클릭하세요',''));$('candidate').disabled=true;}
function controls(){if(!current())return;$('color').value=current().color;$('strength').value=current().strength*100;$('strengthValue').value=Math.round(current().strength*100)+'%';$('layers').replaceChildren();layers.forEach((l,i)=>{const row=document.createElement('div');row.className='layer'+(i===active?' selected':'');const cb=document.createElement('input');cb.type='checkbox';cb.checked=l.visible;cb.setAttribute('aria-label','레이어 '+(i+1)+' 표시');cb.onchange=()=>{snapshot();l.visible=cb.checked;changed();render();};const b=document.createElement('button'),dot=document.createElement('i');dot.style.background=l.color;b.append(dot,document.createTextNode('레이어 '+(i+1)));b.onclick=()=>{if(busy)return;active=i;resetCandidates();controls();render();};row.append(cb,b);$('layers').append(row);});approvalUI();}
let paintWorker,renderRunning=false,renderPending=false,renderSource;
function render(){renderPending=true;if(!frame){frame=requestAnimationFrame(draw);frameTimer=setTimeout(draw,50);}}
function draw(){cancelAnimationFrame(frame);clearTimeout(frameTimer);frame=0;if(!source||renderRunning)return;renderPending=false;renderRunning=true;
 if(!paintWorker){paintWorker=new Worker('./render.worker.mjs',{type:'module'});paintWorker.onmessage=({data:r})=>{renderRunning=false;if(drag&&!r.error){renderPending=true;return;}if(r.error){fail(Error(r.error));}else if(r.image===id&&renderSource===source){lastResult=r.result;ctx.putImageData(new ImageData(showOriginal?source:r.result,w,h),0,0);mctx.clearRect(0,0,w,h);if(!showOriginal&&$('overlay').checked){if(r.overlay)mctx.putImageData(new ImageData(r.overlay,w,h),0,0);for(const p of current()?.points||[]){mctx.beginPath();mctx.arc(p.x*w,p.y*h,5*Math.max(w/800,1),0,Math.PI*2);mctx.fillStyle=p.label?'#44efc5':'#ff637d';mctx.fill();mctx.strokeStyle='#17202b';mctx.lineWidth=2;mctx.stroke();}}$('integrity').textContent='경계 AA · 백그라운드 처리';view.updateCursor();}if(renderPending)render();};paintWorker.onerror=e=>{renderRunning=false;paintWorker.terminate();paintWorker=null;renderSource=null;fail(e);};}
 const message={image:id,active,overlay:$('overlay').checked,layers:layers.map(l=>({mask:l.mask,cacheKey:maskId(l.mask),maskRevision:maskVersions.get(l.mask)||0,color:l.color,strength:l.strength,visible:l.visible}))};if(renderSource!==source){message.source=source;message.w=w;message.h=h;renderSource=source;}paintWorker.postMessage(message);
}
function fit(){view.fit(true);}
function filtered(){const q=$('search').value.toLowerCase(),f=$('filter').value;return files.filter(x=>(f==='all'||x.status===f)&&x.name.toLowerCase().includes(q));}
function list(){const data=filtered();$('count').textContent=`${data.length} / ${files.length}장`;const fragment=document.createDocumentFragment();for(const f of data){const b=document.createElement('button');b.className='file'+(f.id===id?' active':'');b.dataset.imageId=f.id;const im=document.createElement('img');im.loading='lazy';im.src='./thumb/'+f.id+'?v='+f.signature;im.alt='';const s=document.createElement('span');s.append(document.createTextNode(f.name));const small=document.createElement('small');small.textContent=({new:'미작업',working:'작업 중',approved:'정답 확정',skipped:'스킵 · 원본 저장'})[f.status]+(f.prepared?' · 분석 준비됨':'');s.append(small);b.title=f.name;b.append(im,s);b.onclick=()=>select(f.id).catch(fail);fragment.append(b);}$('files').replaceChildren(fragment);}
async function pixels(imageId){const im=new Image();im.src='./image/'+imageId+'?v='+files.find(f=>f.id===imageId)?.signature;await im.decode();if(im.naturalWidth*im.naturalHeight>5000000)throw Error('500만 픽셀 이하 이미지를 사용하세요.');const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0);return {width:c.width,height:c.height,data:x.getImageData(0,0,c.width,c.height).data};}
async function select(next){if(next===id||navigating||exporting||busy)return;navigating=true;try{await preferencesReady;await flush();const [p,s]=await Promise.all([pixels(next),api.read(next)]);ready=false;source=p.data;sourceCanvas=null;w=p.width;h=p.height;id=next;canvas.width=marks.width=w;canvas.height=marks.height=h;lastOverlay=null;layers=[];layers=s?unpack(s):[fresh()];if(!layers.length)layers.push(fresh());approved=!!s?.approved;skipped=!!s?.skipped;metrics={...(s?.metrics||{})};lastAction=0;dirty=false;active=0;history=[];resetCandidates();$('empty').hidden=true;$('filename').textContent=files.find(f=>f.id===id).name;$('dimensions').textContent=`${w} × ${h} px`;$('saveStatus').textContent=s?'저장된 작업 복원':'미작업';status('AI 분석 또는 브러시로 영역을 선택하세요.');controls();$('files').querySelector('.file.active')?.classList.remove('active');$('files').querySelector('[data-image-id="'+id+'"]')?.classList.add('active');fit();render();await boundaryTask('init',{pixels:source.slice().buffer,width:w,height:h});if(files.find(f=>f.id===id)?.prepared)await prepare(id);}finally{navigating=false;}}
$('folder').onclick=async()=>{if(busy||exporting||navigating)return;try{await flush();const r=await api.openFolder();if(!r)return;files=r.files;id=null;source=null;w=h=0;layers=[];worker?.terminate();worker=null;ready=false;canvas.width=marks.width=0;$('empty').hidden=false;$('folderName').textContent=r.folder;list();if(files.length)await select(files[0].id);else status('이 폴더에 PNG, JPG, WebP 이미지가 없습니다.');}catch(e){fail(e);}};
async function move(delta){const data=filtered(),i=data.findIndex(f=>f.id===id),f=data[i+delta];if(f)await select(f.id);}
$('prev').onclick=()=>move(-1).catch(fail);$('next').onclick=()=>move(1).catch(fail);$('search').oninput=$('filter').onchange=list;
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='ArrowLeft')move(-1).catch(fail);if(e.key==='ArrowRight')move(1).catch(fail);if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo();}});
function setBusy(v){v=v||batchPreparing;busy=v;$('analyze').disabled=v;$('color').disabled=v;$('strength').disabled=v;$('candidate').disabled=v||!candidates.length;}
let pendingPrepare=null,batchPreparing=false,stopPrepare=false;
function ensureWorker(){if(worker)return;worker=new Worker('./segment.worker.mjs',{type:'module'});worker.onmessage=async({data:m})=>{if(m.type==='status'){if(!batchPreparing)status(m.text);return;}if(m.type==='ready'){const pending=pendingPrepare;pendingPrepare=null;try{if(m.cache)await api.cacheWrite(pending.id,m.cache);const f=files.find(f=>f.id===pending.id);if(f)f.prepared=true;ready=pending.id===id;pending.resolve();}catch(e){pending.reject(e);}return;}if(m.type==='masks'){candidates=m.candidates;const best=m.scores.indexOf(Math.max(...m.scores));$('candidate').replaceChildren(...m.scores.map((_,i)=>new Option('후보 '+(i+1)+(i===best?' · 추천':''),i)));$('candidate').value=best;await applyCandidate();status(anchorEdit?'선택 완료 · 포함 앵커 위치를 기준으로 인식했습니다.':'다시 인식 완료 · 포함·제외 앵커를 종합했습니다.'+(current().refinement?.unmatched?' 일부 포함 앵커 주변의 마스크를 찾지 못했습니다.':''));}if(m.type==='error'){if(pendingPrepare){pendingPrepare.reject(Error(m.text));pendingPrepare=null;}setBusy(false);fail(Error(m.text));}};worker.onerror=e=>{pendingPrepare?.reject(Error(e.message));pendingPrepare=null;worker.terminate();worker=null;ready=false;setBusy(false);fail(e);};}
async function prepare(imageId){const began=performance.now();setBusy(true);try{ensureWorker();const cache=await api.cacheRead(imageId);const p=cache?null:(imageId===id?{data:source,width:w,height:h}:await pixels(imageId));await new Promise((resolve,reject)=>{pendingPrepare={id:imageId,resolve,reject};worker.postMessage(cache?{type:'restore',cache}:{type:'encode',pixels:p.data.slice().buffer,width:p.width,height:p.height});});}finally{metrics.lastPrepareMs=Math.round(performance.now()-began);if(!batchPreparing)setBusy(false);}}
$('analyze').onclick=async()=>{if(!source||busy||exporting)return;try{await prepare(id);list();status('AI 준비 완료 · '+(metrics.lastPrepareMs/1000).toFixed(1)+'초 · 포함할 곳을 클릭하세요.');}catch(e){fail(e);}};
$('pausePrepare').onclick=()=>{stopPrepare=true;$('pausePrepare').disabled=true;};
$('prepareAll').onclick=async()=>{if(!files.length||busy||exporting||navigating)return;batchPreparing=true;stopPrepare=false;setBusy(true);$('pausePrepare').hidden=false;$('pausePrepare').disabled=false;$('prepPanel').hidden=false;$('prepProgress').max=files.length;let done=0,failed=0;try{await flush();for(const f of files){if(stopPrepare)break;try{if(!f.prepared)await prepare(f.id);}catch(e){failed++;}done++;$('prepProgress').value=done;$('prepText').textContent=done+' / '+files.length+'장 · 실패 '+failed;}ready=false;if(id&&files.find(f=>f.id===id)?.prepared)await prepare(id);list();status((stopPrepare?'분석 준비 중지':'분석 준비 완료')+' · '+done+'장 · 실패 '+failed+'장. 다시 실행하면 준비된 이미지는 건너뜁니다.');}finally{batchPreparing=false;setBusy(false);$('pausePrepare').hidden=true;}};
$('rescan').onclick=async()=>{if(busy||exporting||navigating)return;try{await flush();const previous=files,selected=id,r=await api.rescan();if(!r)return;files=r.files;const changed=files.filter(f=>previous.find(p=>p.id===f.id)?.signature!==f.signature).length;id=null;source=null;layers=[];canvas.width=marks.width=0;ready=false;list();if(files.length)await select(files.some(f=>f.id===selected)?selected:files[0].id);else $('empty').hidden=false;status('위치 스캔 완료 · 새 이미지 또는 교체 '+changed+'장. 교체된 이미지의 이전 마스크와 분석 캐시는 적용하지 않았습니다.');}catch(e){fail(e);}};
$('skip').onclick=async()=>{if(!source||busy||exporting)return;skipped=!skipped;approved=false;dirty=true;revision++;approvalUI();try{await flush();status(skipped?'최종 폴더에 원본 그대로 저장합니다. 학습·베타 데이터에서는 제외합니다.':'스킵을 해제했습니다.');}catch(e){fail(e);}};

function point(e,clamp=true){const b=canvas.getBoundingClientRect(),x=(e.clientX-b.left)/b.width,y=(e.clientY-b.top)/b.height;return clamp?{x:Math.max(0,Math.min(1,x)),y:Math.max(0,Math.min(1,y))}:{x,y};}
function previewErase(ax,ay,bx,by,r){const dx=bx-ax,dy=by-ay,length=Math.hypot(dx,dy),x=Math.max(0,Math.floor(Math.min(ax,bx)-r-2)),y=Math.max(0,Math.floor(Math.min(ay,by)-r-2)),right=Math.min(w,Math.ceil(Math.max(ax,bx)+r+2)),bottom=Math.min(h,Math.ceil(Math.max(ay,by)+r+2));if(right<=x||bottom<=y)return;if(!sourceCanvas){sourceCanvas=document.createElement('canvas');sourceCanvas.width=w;sourceCanvas.height=h;sourceCanvas.getContext('2d').putImageData(new ImageData(source,w,h),0,0);}ctx.save();ctx.beginPath();if(length<.001)ctx.arc(ax,ay,r,0,Math.PI*2);else{const nx=-dy/length*r,ny=dx/length*r,a=Math.atan2(ny,nx);ctx.moveTo(ax+nx,ay+ny);ctx.lineTo(bx+nx,by+ny);ctx.arc(bx,by,r,a,a-Math.PI,true);ctx.lineTo(ax-nx,ay-ny);ctx.arc(ax,ay,r,a-Math.PI,a-2*Math.PI,true);}ctx.closePath();ctx.clip();ctx.drawImage(sourceCanvas,x,y,right-x,bottom-y,x,y,right-x,bottom-y);ctx.restore();}
function paint(p){const r=Number($('brush').value)/2,prev=lastPoint||p,px=p.x*w,py=p.y*h,ax=prev.x*w,ay=prev.y*h,mask=current().mask,value=tool==='erase'?0:255;brushSegment(mask,w,h,ax,ay,px,py,r,value);if(tool==='paint'){ctx.save();ctx.strokeStyle=current().color;ctx.fillStyle=current().color;ctx.globalAlpha=current().strength;ctx.lineWidth=r*2;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(px,py);ctx.stroke();if(!lastPoint){ctx.beginPath();ctx.arc(px,py,r,0,Math.PI*2);ctx.fill();}ctx.restore();}else previewErase(ax,ay,px,py,r);lastPoint=p;record('brushMoves');}
async function applyNegativeAnchor(p){snapshot();current().points.push({...p,label:0});record('excludeClicks');current().promptHistory=[...(current().promptHistory||[]),{...p,label:0,activeMs:metrics.activeMs||0}];setBusy(true);try{const result=await boundaryTask('negative',{mask:current().mask,points:[p],protectedPoints:current().points.filter(q=>q.label===1),options:boundaryOptions()});current().mask=result.mask;current().refinedMask=result.mask.slice();resetCandidates();invalidateMask();changed();render();status('제외 앵커 적용 · 가까운 선 경계 안쪽에서 '+result.removed+'픽셀을 제거했습니다.');}finally{setBusy(false);}}
canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{if(!source||busy||navigating||exporting||showOriginal)return;const p=point(e);if(e.ctrlKey){const rect=canvas.getBoundingClientRect();const i=current().points.findIndex(q=>Math.hypot((q.x-p.x)*rect.width,(q.y-p.y)*rect.height)<=12);if(i>=0){snapshot();current().points.splice(i,1);invalidateMask();changed();render();status('앵커 삭제 · 부위 다시 인식 버튼으로 마스크를 갱신하세요.');}return;}if(tool==='paint'||tool==='erase'){snapshot();record('brushStrokes');drag=true;lastPoint=null;canvas.setPointerCapture(e.pointerId);paint(point(e,false));}else{if(!ready){status('먼저 AI 분석을 누르세요.');return;}const label=tool==='negative'||e.button===2?0:1;if(!label&&!current().points.length){status('포함할 곳을 먼저 클릭하세요.');return;}if(!label){applyNegativeAnchor(p).catch(fail);return;}snapshot();anchorEdit={mask:current().mask.slice(),point:{...p,label}};current().points.push({...p,label});record('includeClicks');current().promptHistory=[...(current().promptHistory||[]),{...p,label,activeMs:metrics.activeMs||0}];setBusy(true);render();worker.postMessage({type:'decode',points:current().points.filter(q=>q.label===1)});}};
canvas.onpointermove=e=>{if(drag)paint(point(e,false));};canvas.onpointerup=canvas.onpointercancel=()=>{if(!drag)return;drag=false;lastPoint=null;view.updateCursor();invalidateMask();changed();render();};
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));});
$('brush').oninput=()=>{$('brushValue').value=$('brush').value+' px';};$('candidate').onchange=()=>{if(!current())return;snapshot();applyCandidate();};
$('color').onchange=()=>{const value=$('color').value;if(!['#ffffff','#000000'].includes(value))return;defaultColor=value;preferenceSave=preferenceSave.catch(()=>{}).then(()=>api.preferencesSave({color:value}));preferenceSave.catch(fail);if(!current()||busy)return;snapshot();current().color=value;changed();controls();render();};
$('strength').onfocus=()=>{if(current())snapshot();};$('strength').oninput=()=>{if(!current()||busy)return;current().strength=Number($('strength').value)/100;$('strengthValue').value=$('strength').value+'%';changed();render();};

$('overlay').onchange=render;$('original').onclick=()=>{showOriginal=!showOriginal;$('original').textContent=showOriginal?'편집 결과':'원본 보기';render();};
$('clear').onclick=()=>{if(!current()||busy)return;snapshot();current().mask.fill(0);current().points=[];invalidateMask();resetCandidates();changed();render();};
function undo(){if(busy||exporting||navigating)return;record('undoCount');const s=history.pop();if(s){layers=s.layers;active=s.active;resetCandidates();changed();controls();render();}};
$('newLayer').onclick=()=>{if(!source||busy)return;if(layers.length>=30){status('이미지당 레이어는 최대 30개입니다.');return;}snapshot();layers.push(fresh());active=layers.length-1;resetCandidates();changed();controls();render();};
$('deleteLayer').onclick=()=>{if(!current()||busy)return;snapshot();layers.splice(active,1);if(!layers.length)layers.push(fresh());active=Math.min(active,layers.length-1);resetCandidates();changed();controls();render();};
$('approve').onclick=async()=>{if(!source||busy)return;if(!layers.some(l=>l.mask.some(x=>x))){status('확정할 마스크가 없습니다.');return;}skipped=false;approved=!approved;dirty=true;revision++;approvalUI();try{await flush();status(approved?'학습용 정답으로 저장했습니다.':'정답 확정을 해제했습니다.');}catch(e){fail(e);}};
function png(data,width,height){const c=document.createElement('canvas');c.width=width;c.height=height;c.getContext('2d').putImageData(new ImageData(data,width,height),0,0);return c.toDataURL('image/png');}
const finalizeAll=document.createElement('button');finalizeAll.id='finalizeAll';finalizeAll.textContent='전체 일괄처리';finalizeAll.title='전체 이미지: 결과가 변경되면 정답 확정, 원본과 같으면 스킵';$('batch').before(finalizeAll);
finalizeAll.onclick=async()=>{
 if(!files.length||busy||exporting||navigating||drag)return;
 exporting=true;setBusy(true);
 const controlsToLock=[...document.querySelectorAll('button,input,select')].map(e=>[e,e.disabled]);controlsToLock.forEach(([e])=>e.disabled=true);
 const checker=new Worker('./batch-result.worker.mjs',{type:'module'});
 let done=0,accepted=0,skips=0;const failures=[];
 $('prepPanel').hidden=false;$('prepProgress').max=files.length;$('prepProgress').value=0;
 try{
  await flush();
  for(const f of files){
   $('prepText').textContent=`전체 일괄처리 ${done} / ${files.length}장 · ${f.name}`;
   try{
    const saved=await api.read(f.id),p=await pixels(f.id);
    const state=saved||{version:2,width:p.width,height:p.height,layers:[],metrics:{}};
    const decoded=unpack(state);
    const changed=decoded.some(l=>l.visible!==false&&l.strength>0&&l.mask.some(v=>v))?await new Promise((resolve,reject)=>{checker.onmessage=({data:r})=>r.error?reject(Error(r.error)):resolve(r.changed);checker.onerror=e=>reject(Error(e.message));checker.postMessage({source:p.data,width:p.width,height:p.height,layers:decoded});}):false;
    state.approved=changed;state.skipped=!changed;
    await api.save(f.id,state);
    f.status=changed?'approved':'skipped';if(changed)accepted++;else skips++;
    if(f.id===id){approved=changed;skipped=!changed;dirty=false;approvalUI();}
   }catch(e){failures.push(f.name+': '+(e.message||e));}
   done++;$('prepProgress').value=done;
  }
  list();const message=`전체 일괄처리 완료 · 정답 확정 ${accepted}장 · 스킵 ${skips}장 · 실패 ${failures.length}장`;
  $('prepText').textContent=message;$('prepText').title=failures.join('\n');status(message+(failures.length?' · '+failures[0]:''));$('saveStatus').textContent=message;
 }catch(e){fail(e);}finally{checker.terminate();exporting=false;setBusy(false);controlsToLock.forEach(([e,disabled])=>e.disabled=disabled);setBusy(false);}
};
async function exportItems(kind){if(exporting||busy||navigating)return;try{await flush();const items=files.filter(f=>kind==='dataset'?f.status==='approved':f.status!=='new');if(!items.length){status(kind==='dataset'?'정답 확정한 이미지가 없습니다.':'저장된 작업이 없습니다.');return;}const token=await api.destination(kind);if(!token)return;exporting=true;document.body.classList.add('exporting');const manifest=[];for(let i=0;i<items.length;i++){const f=items[i],s=await api.read(f.id);if(!s)continue;const ls=unpack(s);status(`내보내는 중 ${i+1} / ${items.length}`);if(kind==='results'&&s.skipped){await api.write(token,f.id,{skipped:true});continue;}if(kind==='results'){const p=await pixels(f.id);await api.write(token,f.id,{image:encodeResult(compose(p.data,ls,undefined,p.width,p.height),p.width,p.height,f.name)});}else{const nonempty=ls.filter(l=>l.mask.some(x=>x));const masks=nonempty.map(l=>{const rgba=new Uint8ClampedArray(s.width*s.height*4);for(let p=0;p<l.mask.length;p++){rgba[p*4]=rgba[p*4+1]=rgba[p*4+2]=l.mask[p]?255:0;rgba[p*4+3]=255;}return png(rgba,s.width,s.height);});await api.write(token,f.id,{masks});manifest.push({id:f.id,annotation:f.id+'/annotation.json',split:parseInt(f.id.slice(0,2),16)%5===0?'validation':'train'});}}const dir=await api.finish(token,{images:manifest});status('내보내기 완료: '+dir);}catch(e){fail(e);}finally{exporting=false;document.body.classList.remove('exporting');}}
$('batch').onclick=()=>exportItems('results');$('dataset').onclick=()=>exportItems('dataset');
setupSubmission({api,button:$('beta'),getFiles:()=>files,flush,pixels,png,unpack,lock:v=>{exporting=v;},blocked:()=>busy||exporting||navigating,status});
api.onClose(async()=>{try{if(busy||exporting)throw Error('AI 분석 또는 내보내기가 끝난 뒤 닫아주세요.');await flush();api.closeReady();}catch(e){api.closeFailed(e.message);}});
