export function setupSubmission({api,button,getFiles,flush,pixels,png,unpack,lock,blocked,status}){
 const modal=document.createElement('dialog');modal.id='betaDialog';modal.innerHTML=`<div class="beta-head"><div><h2>베타 제출 패키지</h2><p>선택한 이미지 전체와 마스크를 ZIP으로 저장합니다. 자동 전송하지 않습니다.</p></div><button id="betaClose">닫기</button></div><div class="beta-grid"><nav><p id="betaCount"></p><div id="betaFiles"></div></nav><section><canvas id="betaPreview"></canvas><p id="betaImageName"></p><div id="betaLayers"></div><p class="hint">레이어를 제외해도 선택한 원본 이미지 전체가 포함됩니다. 학습 마스크에는 테두리 혼합을 적용하지 않습니다.</p></section><section><label>출처 묶음 <input id="betaGroup" maxlength="100" placeholder="예: 내그림-시리즈A"></label><label>그림체 특징 <input id="betaStyle" maxlength="200" placeholder="예: 가는 선, 셀 채색, 복잡한 배경"></label><label>이미지 제공 근거<select id="betaProvenance"><option value="">선택하세요</option><option value="own">직접 제작한 이미지</option><option value="permission">제공 허락을 받은 이미지</option><option value="generated">제공 가능한 생성 이미지</option></select></label><button id="betaApplyMetadata" class="wide">이 정보를 선택한 이미지에 적용</button><p id="betaHistory" class="hint"></p><label>전달할 설명<textarea id="betaNotes" maxlength="2000" rows="3" placeholder="불편했던 점이나 반복된 인식 오류"></textarea></label></section></div><div class="beta-consent"><p id="betaNotice"></p><label class="check"><input id="betaRights" type="checkbox"> 선택한 이미지와 마스크를 제공할 권한이 있습니다.</label><label class="check"><input id="betaAnalysis" type="checkbox"> 선택한 데이터를 오류 분석·품질 평가에 사용하는 데 동의합니다.</label><label class="check"><input id="betaTraining" type="checkbox"> 모델 학습 및 개선된 모델 배포에도 동의합니다. (선택)</label><div class="beta-foot"><span id="betaMessage" role="status"></span><button id="betaCreate" class="primary">동의한 내용으로 ZIP 만들기</button></div></div>`;document.body.append(modal);
 const upload=document.createElement('div');upload.innerHTML='<label>베타 초대 코드 <input id="betaInvite" type="password" autocomplete="off"></label><label class="check"><input id="betaCloudConsent" type="checkbox"> 생성한 ZIP의 이미지·마스크·동의 기록을 앱 운영자의 비공개 Cloudflare R2 저장소로 전송합니다.</label><button id="betaUpload" disabled>생성한 ZIP을 R2에 제출</button><p class="hint">ZIP당 최대 90 MiB · 업로드 버튼을 눌러야 전송합니다.</p>';modal.append(upload);let lastSubmission=null;
 const $=id=>modal.querySelector('#'+id);let entries=[],currentEntry,currentState,currentImage,profile,creating=false,loading=false,requestId=0;
 const message=t=>$('betaMessage').textContent=t;
 function updateCount(){$('betaCount').textContent=entries.filter(e=>e.included).length+'장 선택 · 최대 50장';}
 async function select(e){const rid=++requestId;loading=true;currentEntry=e;$('betaGroup').value=e.group;$('betaStyle').value=e.style;$('betaProvenance').value=e.provenance;$('betaImageName').textContent=e.name;try{const [state,image]=await Promise.all([api.read(e.id),pixels(e.id)]);if(rid!==requestId)return;if(!state?.approved||state.skipped)throw Error('정답 확정 상태가 변경됐습니다.');currentState=state;currentImage=image;const layers=unpack(state);if(!e.layers)e.layers=layers.map((l,i)=>l.mask.some(x=>x)?i:-1).filter(i=>i>=0);$('betaLayers').replaceChildren();layers.forEach((l,i)=>{if(!l.mask.some(x=>x))return;const label=document.createElement('label');label.className='check';const input=document.createElement('input');input.type='checkbox';input.checked=e.layers.includes(i);input.onchange=()=>{e.layers=input.checked?[...e.layers,i].sort((a,b)=>a-b):e.layers.filter(j=>j!==i);preview();};label.append(input,document.createTextNode('레이어 '+(i+1)));$('betaLayers').append(label);});$('betaHistory').textContent=layers.some(l=>l.initialMask)?'AI 원본·보정 마스크와 이용 가능한 클릭 기록을 함께 포함합니다.':'기존 작업: AI 초기 결과 기록이 없습니다. 최종 마스크와 이용 가능한 정보만 포함합니다.';preview();message('원본과 제출할 레이어를 확인하세요.');}catch(err){e.included=false;message(err.message);}finally{if(rid===requestId){loading=false;updateCount();}}}
 function preview(){if(!currentImage||!currentState)return;const c=$('betaPreview'),p=currentImage;c.width=p.width;c.height=p.height;const data=p.data.slice(),layers=unpack(currentState);for(const i of currentEntry.layers||[]){const l=layers[i];for(let k=0;k<l.mask.length;k++)if(l.mask[k]){data[k*4]=data[k*4]*.6+30*.4;data[k*4+1]=data[k*4+1]*.6+220*.4;data[k*4+2]=data[k*4+2]*.6+180*.4;}}c.getContext('2d').putImageData(new ImageData(data,p.width,p.height),0,0);}
 for(const [field,key] of [['betaGroup','group'],['betaStyle','style'],['betaProvenance','provenance']])$(field).oninput=()=>{if(currentEntry)currentEntry[key]=$(field).value;};
 $('betaApplyMetadata').onclick=()=>{if(!currentEntry)return;for(const e of entries)if(e.included){e.group=currentEntry.group;e.style=currentEntry.style;e.provenance=currentEntry.provenance;}message('선택한 이미지에 출처·그림체 정보를 적용했습니다.');};
 button.onclick=async()=>{if(blocked())return;try{await flush();const files=getFiles().filter(f=>f.status==='approved');if(!files.length){status('먼저 제출할 이미지의 마스크를 정답 확정하세요.');return;}lastSubmission=null;$('betaUpload').disabled=true;$('betaCloudConsent').checked=false;profile=await api.betaProfile();entries=files.map(f=>({...f,included:false,layers:null,group:'',style:'',provenance:''}));$('betaFiles').replaceChildren();for(const e of entries){const row=document.createElement('div');row.className='beta-file';const cb=document.createElement('input');cb.type='checkbox';cb.setAttribute('aria-label',e.name+' 제출');cb.onchange=()=>{e.included=cb.checked;updateCount();select(e);};const b=document.createElement('button');b.textContent=e.name;b.title=e.name;b.onclick=()=>select(e);row.append(cb,b);$('betaFiles').append(row);}$('betaNotice').textContent=profile.notice.text;for(const id of ['betaRights','betaAnalysis','betaTraining'])$(id).checked=false;$('betaNotes').value='';modal.showModal();updateCount();await select(entries[0]);}catch(e){status('제출 준비 실패: '+e.message);}};
 $('betaUpload').onclick=async()=>{if(creating||!lastSubmission)return;if(!$('betaCloudConsent').checked){message('R2 전송 동의에 체크하세요.');return;}try{creating=true;lock(true);$('betaUpload').disabled=true;message('R2 업로드 중…');const done=await api.betaUpload(lastSubmission,$('betaInvite').value.trim());message('R2 제출 완료 · '+done.submissionId);$('betaInvite').value='';}catch(e){message(e.message);}finally{creating=false;lock(false);$('betaUpload').disabled=false;}};
 const close=()=>{if(creating)return;requestId++;currentState=currentImage=null;modal.close();};$('betaClose').onclick=close;modal.addEventListener('cancel',e=>{e.preventDefault();close();});
 $('betaCreate').onclick=async()=>{if(creating||loading)return;const selected=entries.filter(e=>e.included);if(!selected.length||selected.length>50){message('1~50장의 이미지를 선택하세요.');return;}if(!selected.every(e=>e.layers?.length&&e.group.trim()&&e.style.trim()&&e.provenance)){message('선택한 모든 이미지의 레이어·출처 묶음·그림체·제공 근거를 확인하세요.');return;}if(!$('betaRights').checked||!$('betaAnalysis').checked){message('제공 권한과 오류 분석 동의가 필요합니다. 학습 동의는 선택입니다.');return;}let token;try{creating=true;lock(true);$('betaCreate').disabled=true;$('betaClose').disabled=true;const result=await api.betaBegin({items:selected.map(({id,layers,group,style,provenance})=>({id,layers,group,style,provenance})),consent:{analysis:true,rights:true,training:$('betaTraining').checked,noticeVersion:profile.notice.version},notes:$('betaNotes').value});if(!result){message('저장을 취소했습니다.');return;}token=result.token;for(let i=0;i<selected.length;i++){message('패키지 생성 중 '+(i+1)+' / '+selected.length);const image=await pixels(selected[i].id);await api.betaAdd(token,selected[i].id,png(image.data,image.width,image.height));}const done=await api.betaFinish(token);lastSubmission=done.submissionId;$('betaUpload').disabled=false;token=null;message('ZIP 저장 완료 · 제출 ID: '+done.submissionId);status('베타 패키지 저장 완료: '+done.path+' · 서버로 전송하지 않았습니다.');}catch(e){message('패키지 생성 실패: '+e.message);if(token)await api.betaCancel(token).catch(()=>{});}finally{creating=false;lock(false);$('betaCreate').disabled=false;$('betaClose').disabled=false;}};
}
