// View state only: these interactions never change image pixels or masks.
export function setupViewport({viewport,canvas,wrap,zoom,brush,brushValue,getSize,getTool,canPaint}){
 const stage=document.createElement('div');stage.id='imageStage';wrap.before(stage);stage.append(wrap);
 const cursor=document.createElement('div');cursor.id='brushCursor';cursor.hidden=true;document.body.append(cursor);
 let scale=1,fitMode=true,space=false,panning=null,lastMouse=null;
 const custom=new Option('','custom');zoom.append(custom);
 function updateCursor(){const usable=lastMouse&&canPaint()&&['paint','erase'].includes(getTool())&&!space&&!panning;cursor.hidden=!usable;canvas.style.cursor=space?(panning?'grabbing':'grab'):usable?'none':'crosshair';viewport.style.cursor=space?(panning?'grabbing':'grab'):'';if(!usable)return;const rect=canvas.getBoundingClientRect();if(lastMouse.x<rect.left||lastMouse.y<rect.top||lastMouse.x>rect.right||lastMouse.y>rect.bottom){cursor.hidden=true;return;}const d=Number(brush.value)*scale;cursor.style.width=d+'px';cursor.style.height=d+'px';cursor.style.left=lastMouse.x+'px';cursor.style.top=lastMouse.y+'px';cursor.dataset.mode=getTool();}
 function layout(next,anchor){const {w,h}=getSize();if(!w||!h)return;const vr=viewport.getBoundingClientRect(),cr=canvas.getBoundingClientRect();const ax=anchor?.x??vr.left+viewport.clientWidth/2,ay=anchor?.y??vr.top+viewport.clientHeight/2;const px=anchor?(ax-cr.left)/scale:w/2,py=anchor?(ay-cr.top)/scale:h/2;scale=Math.max(.05,Math.min(8,next));const padX=viewport.clientWidth/2,padY=viewport.clientHeight/2;stage.style.width=w*scale+2*padX+'px';stage.style.height=h*scale+2*padY+'px';wrap.style.left=padX+'px';wrap.style.top=padY+'px';canvas.style.width=w*scale+'px';canvas.style.height=h*scale+'px';viewport.scrollLeft=padX+px*scale-(ax-vr.left);viewport.scrollTop=padY+py*scale-(ay-vr.top);if(!fitMode){custom.textContent=Math.round(scale*100)+'%';zoom.value='custom';}updateCursor();}
 function fit(){const {w,h}=getSize();if(!w)return;layout(fitMode?Math.min((viewport.clientWidth-48)/w,(viewport.clientHeight-48)/h,1):scale);}
 zoom.onchange=()=>{fitMode=zoom.value==='fit';if(fitMode)fit();else if(zoom.value!=='custom')layout(Number(zoom.value));};
 viewport.addEventListener('wheel',e=>{if(!getSize().w)return;e.preventDefault();fitMode=false;layout(scale*Math.exp(-Math.max(-200,Math.min(200,e.deltaY*(e.deltaMode===1?16:1)))*.002),{x:e.clientX,y:e.clientY});},{passive:false});
 const editing=e=>e.target.isContentEditable||e.target.tagName==='TEXTAREA'||(e.target.tagName==='INPUT'&&!['range','checkbox','color','button'].includes(e.target.type));
 window.addEventListener('keydown',e=>{if(editing(e))return;if(e.code==='Space'){e.preventDefault();space=true;updateCursor();}if(e.code==='BracketLeft'||e.code==='BracketRight'){e.preventDefault();const n=Number(brush.value),step=n<20?1:n<100?5:10;brush.value=Math.max(Number(brush.min),Math.min(Number(brush.max),n+(e.code==='BracketRight'?step:-step)));brushValue.value=brush.value+' px';updateCursor();}},true);
 window.addEventListener('keyup',e=>{if(e.code==='Space'){e.preventDefault();space=false;updateCursor();}},true);
 viewport.addEventListener('pointerdown',e=>{if(!space||!getSize().w||e.button!==0)return;e.preventDefault();e.stopImmediatePropagation();panning={x:e.clientX,y:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop};viewport.setPointerCapture(e.pointerId);updateCursor();},true);
 viewport.addEventListener('pointermove',e=>{lastMouse={x:e.clientX,y:e.clientY};if(panning){e.preventDefault();e.stopImmediatePropagation();viewport.scrollLeft=panning.left-(e.clientX-panning.x);viewport.scrollTop=panning.top-(e.clientY-panning.y);}updateCursor();},true);
 const stop=e=>{if(panning){e.stopImmediatePropagation();panning=null;updateCursor();}};viewport.addEventListener('pointerup',stop,true);viewport.addEventListener('pointercancel',stop,true);viewport.addEventListener('lostpointercapture',()=>{panning=null;updateCursor();});
 viewport.addEventListener('pointerleave',()=>{lastMouse=null;updateCursor();});window.addEventListener('blur',()=>{space=false;panning=null;lastMouse=null;updateCursor();});viewport.addEventListener('scroll',updateCursor);brush.addEventListener('input',updateCursor);document.addEventListener('click',updateCursor);
 new ResizeObserver(()=>fit()).observe(viewport);
 return {fit,updateCursor};
}
